name: Haskell webasm compile
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix shell https://gitlab.haskell.org/ghc/ghc-wasm-meta/-/archive/master/ghc-wasm-meta-master.tar.gz --command "wasm32-wasi-cabal build --minimize-conflict-set --allow-newer=base --allow-newer=deepseq --allow-newer=template-haskell --allow-newer=pretty"
      - run: ls
      
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'release.zip'

      - run: ls

      - name: Create Release
        uses: softprops/action-gh-release@v1
#        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name : dist
          prerelease : true
#           draft: true
          files: release.zip